app = "backendreportmanager"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.ports]
    port = 80
    handlers = ["http"]
    force_https = true
  [services.ports]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8080"